# Generated by Django 2.0.2 on 2018-06-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0002_auto_20180609_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField( max_length=500)),
                ('percentage', models.IntegerField(default=0)),
                ('viewcount', models.IntegerField(default=0)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Profile')),
            ],
        ),
    ]
